-- Analytics layer: Dynamic table joining customers and orders

DEFINE DYNAMIC TABLE {{db}}.ANALYTICS.CUSTOMER_ORDERS
WAREHOUSE = PIPELINE_WH{{env_suffix}}
TARGET_LAG = '1 hour'
AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL,
    COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS LIFETIME_VALUE,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
FROM {{db}}.RAW.CUSTOMERS c
LEFT JOIN {{db}}.RAW.ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL;
